# Generated by Django 3.2.3 on 2021-06-09 13:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('duel', '0003_auto_20210607_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='voted_users',
            field=models.ManyToManyField(related_name='post_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
