# Generated by Django 3.2.3 on 2021-06-09 14:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('duel', '0004_alter_post_voted_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='voted_users',
            field=models.ManyToManyField(related_name='middleTab', to=settings.AUTH_USER_MODEL),
        ),
    ]
