# Generated by Django 3.2.4 on 2021-06-21 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('duel', '0005_alter_post_voted_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='loses',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                    verbose_name='Автор'),
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.TextField(max_length=20)),
                ('admin_user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner',
                                   to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(blank=True, default='users', related_name='users',
                                                 to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
