# Generated by Django 3.2.4 on 2021-06-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('duel', '0006_auto_20210621_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='elimination_type',
            field=models.BooleanField(default=False),
        ),
    ]
