# Generated by Django 3.2.4 on 2021-06-23 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('duel', '0006_auto_20210623_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='voted_users',
            field=models.ManyToManyField(null=True, related_name='middleTab', to=settings.AUTH_USER_MODEL),
        ),
    ]
