# Generated by Django 3.2.4 on 2021-06-23 07:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('duel', '0007_organisation_elimination_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organisation',
        ),
    ]
