# Generated by Django 3.2.4 on 2021-06-23 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('duel', '0009_organisation_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='org_id',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE,
                                    to='duel.organisation'),
        ),
    ]
