# Generated by Django 3.2.4 on 2021-06-23 07:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('duel', '0010_profile_org_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='org_id',
            new_name='org',
        ),
    ]
