# Generated by Django 3.2.4 on 2021-06-23 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('duel', '0011_rename_org_id_profile_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='org',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='duel.organisation'),
        ),
    ]
