# Generated by Django 3.2.4 on 2021-06-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('duel', '0012_alter_profile_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='organisation_loses',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='post',
            name='organisation_rate',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
