# Generated by Django 3.2.4 on 2021-06-23 14:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('duel', '0007_alter_post_voted_users'),
        ('duel', '0013_auto_20210623_1559'),
    ]

    operations = [
    ]
