# Generated by Django 3.2.4 on 2021-06-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('duel', '0014_merge_20210623_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='org_name',
            field=models.TextField(max_length=20, verbose_name='Название организации'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='vote_type',
            field=models.BooleanField(default=False, verbose_name='Каждая работа c каждой'),
        ),
    ]
